### ISSUE TITLE
Buttons are too close for unsubscribe mobile view

### ISSUE THREAD

**Issue by lshaowei18** [opengovsg/postmangovsg#620] opened 2020-07-28 09:54 UTC
**Describe the bug**
![Screenshot_20200728-173406_Chrome](https://user-images.githubusercontent.com/33112945/88650441-5171c280-d0fb-11ea-86eb-a31699e56336.jpg)
Taken on samsung S7.

**Comment by pregnantboy** [comment] 2020-07-28 10:32
set `minButtonWidth` attribute for TextButton

**Comment by lamkeewei** [comment] 2020-07-29 03:53
> set `minButtonWidth` attribute for TextButton

`minButtonWidth` is already set. I think the issue is because in mobile, `min-width` is unset for all buttons based on the button mixins. I'll make the button stack vertically instead for now until Sarah reviewed all our mobile layouts.

**Comment by lamkeewei** [comment] 2020-07-29 06:55
Fixed in `unsubscribe` branch.

<img width=300 src='https://user-images.githubusercontent.com/3666479/88766870-5c842b80-d1ab-11ea-831b-56158e69c9c6.png' />

**Closed by lamkeewei** 2020-07-29 06:55 UTC
Labels: bug
