### ISSUE TITLE
Invalid email not reflected in Status ERROR

### ISSUE THREAD

**Issue by cuscsl03** [opengovsg/postmangovsg#326] opened 2020-05-28 08:37 UTC
**Describe the bug**
I added an invalid email in my list of emails to send, but it is not shown as ERROR in the status

**To Reproduce**
Add invalid email in list of emails to send, and send the email in postman.

**Expected behavior**
The invalid email should be reflected as 1 count as ERROR in the status.

**Comment by jeantanzj** [comment] 2020-06-01 09:08
@cuscsl03 
Currently, we check for invalid format of emails, eg `strangemail@x%6z,com`. This should display an error when you upload a csv.

Errors on the campaign dashboard refer to the ones that have failed to be sent (for example, something went wrong when we tried to connect to the email provider). 

We are still working on providing the list of emails that bounce or do not exist (https://github.com/opengovsg/postmangovsg/issues/303), which I presume is what you meant by 'invalid email'.

**Comment by jeantanzj** [comment] 2020-06-01 09:09
Closed as duplicate of https://github.com/opengovsg/postmangovsg/issues/303

**Closed by jeantanzj** 2020-06-01 09:09 UTC
Labels: bug
