### ISSUE TITLE
Outlook reply bug - first two sentences repeated when recipient replies

### ISSUE THREAD

**Issue by syan-syan** [opengovsg/postmangovsg#1304] opened 2021-08-19 10:11 UTC
When recipient replies on Outlook, the first ~2 lines will be repeated above the header. This is similar to the bug MJ found before.

**Comment by tan-zx** [comment] 2022-09-17 02:49
@stanleynguyen can close this one right? it's a feature and not a bug 😂 to get the preview to work properly?

**Comment by stanleynguyen** [comment] 2023-02-17 09:17
> @stanleynguyen can close this one right? it's a feature and not a bug 😂 to get the preview to work properly?

Closing

**Closed by stanleynguyen** 2023-02-17 09:17 UTC
Labels: bug, P2
